#                                                 ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥
#                                                   ğŸ’»Staff Utils ConfigğŸ’»
#                                                   ğŸ”¥Coded By Mike3132ğŸ”¥
#                                                   ğŸ’»Staff Utils ConfigğŸ’»
#                                                 ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥

Version: 'Version 4.0'
ConfigVersion: '4.0'
##### WARNING: DO NOT CHANGE ANYTHING ABOVE THIS LINE IT WILL BREAK THE PLUGIN!#####

#âœâœâœâœâœPermissionsâœâœâœâœâœ
#StaffUtils.Command.Freeze > Allows players to freeze another
#StaffUtils.Command.Spectate > Allows players to use the spectate command
#StaffUtils.Command.Xray > Allows players to use the xray command


#âœâœâœâœâœPermissionsâœâœâœâœâœ

#####You can Modify the following how you wish#####

#âœâœâœâœâœ These are the blocks that will be shown when someone uses /xray (Anything not in this list will be hidden)âœâœâœâœâœ
#â˜ â˜ â˜ â˜  You must use all capital letters, and DO NOT MODIFY "XrayBlocks" it will break the plugin.â˜ â˜ â˜ â˜ 
#ğŸ“ğŸ“ğŸ“ğŸ“ For a full list of blocks see <https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html>ğŸ“ğŸ“ğŸ“ğŸ“

#If this is set to true then when someone uses /xray they will be given night vision.
XrayNightVision: true

XrayBlocks:
  - "COAL_ORE"
  - "DEEPSLATE_COAL_ORE"
  - "COPPER_ORE"
  - "DEEPSLATE_COPPER_ORE"
  - "IRON_ORE"
  - "DEEPSLATE_IRON_ORE"
  - "GOLD_ORE"
  - "DEEPSLATE_GOLD_ORE"
  - "REDSTONE_ORE"
  - "DEEPSLATE_REDSTONE_ORE"
  - "EMERALD_ORE"
  - "DEEPSLATE_EMERALD_ORE"
  - "LAPIS_ORE"
  - "DEEPSLATE_LAPIS_ORE"
  - "DIAMOND_ORE"
  - "DEEPSLATE_DIAMOND_ORE"
  - "NETHER_QUARTZ_ORE"
  - "NETHER_GOLD_ORE"
  - "ANCIENT_DEBRIS"



#See messages.yml for all configurable plugin messages
#â™ If you have any questions please join my discord, open a support ticket and @Mike3132
#â™ https://discord.gg/ePQGvQuzG3
#â™ Thanks for downloading and have a wonderful day

#â™›â™›â™›â™›â™› END OF CONFIG â™›â™›â™›â™›â™›
#This is the default config file.